```yaml
name: vidcommentary
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - transformers
      - opencv-python
      - pillow
      - accelerate
      - sentencepiece