defaults:
  - _self_

text_encoder_cfg:
  encoder: bert-base-uncased
  lora: true
  input_dim: 768     # BERT's hidden size
  output_dim: 768
  freeze: false

vision_encoder_cfg:
  encoder: openai/clip-vit-base-patch32
  lora: false
  input_dim: 768     # ViT's patch embedding size
  output_dim: 768
  freeze: false

fusion_cfg:
  fusion_type: concat
  input_dim: 768      # Optional: only used if projecting embeddings after concat
  output_dim: 768

decoder_cfg:
  decoder: distilgpt2
  lora: true
  input_dim: 768      # Match fusion output_dim
  hidden_dim: 768
  output_dim: 768
  freeze: false

trainer:
  precision: 32
  accelerator: mps
  devices: 1
  batch_size: 4
  lr: 1e-5
  device: mps
  epochs: 5
  output_dir: /Users/vishwajeethogale/Desktop/Research/video-commentary-ai/checkpoints
  max_seq_length: 128
  mlm_probability: 0.15
  save_steps: 500
  logging_steps: 100

data:
  captions_dir: /Users/vishwajeethogale/Desktop/Research/video-commentary-ai/captions_csv
  frames_dir: /Users/vishwajeethogale/Desktop/Research/video-commentary-ai/frames
  batch_size: 3
  num_workers: 4
  pin_memory: false
  use_csv: True

inference:
  batch_size: 1
  num_workers: 0
  pin_memory: false
  max_length: 128
  top_k: 50
  top_p: 0.95
  temperature: 1.0
  image_size: 224
  num_beams: 5
  image_path: /Users/vishwajeethogale/Desktop/Research/video-commentary-ai/frames/Nasogastric tube insertion_clip_0.0s_to_175.0s/frame_0085.jpg