defaults:
  - _self_

text_encoder_cfg:
  encoder: bert-base-uncased
  lora: true
  input_dim: 768     # BERT's hidden size
  output_dim: 768
  freeze: false

vision_encoder_cfg:
  encoder: swin_base_patch4_window7_224
  lora: false
  input_dim: 768     # ViT's patch embedding size
  output_dim: 1000
  freeze: false

fusion_cfg:
  fusion_type: concat
  input_dim: 768      # Optional: only used if projecting embeddings after concat
  output_dim: 768

decoder_cfg:
  decoder: facebook/bart-large
  lora: true
  input_dim: 768      # Match fusion output_dim
  output_dim: 768
  freeze: false

trainer:
  precision: 32
  accelerator: mps
  devices: 2
  batch_size: 4
  lr: 1e-5
  device: mps
  epochs: 5

  max_seq_length: 128
  mlm_probability: 0.15
  output_dir: ./mlm_checkpoints
  save_steps: 500
  logging_steps: 100

data:
  captions_dir: /Users/vishwajeethogale/Desktop/Research/video-commentary-ai/captions_csv
  frames_dir: /Users/vishwajeethogale/Desktop/Research/video-commentary-ai/frames
  batch_size: 3
  num_workers: 4
  pin_memory: true
