defaults:
  - _self_

text_encoder_cfg:
  encoder: bert-base-uncased
  lora: true
  input_dim: 768     # BERT's hidden size
  output_dim: 768
  freeze: false

vision_encoder_cfg:
  encoder: swin_base_patch4_window7_224
  lora: false
  input_dim: 768     # ViT's patch embedding size
  output_dim: 1000
  freeze: false
audio_encoder_cfg:
  encoder: transformer_cls
  lora: false
  input_dim: 768     # Whisper's hidden size
  n_mfcc: 13
  freeze: false
fusion_cfg:
  fusion_type: concat
  input_dim: 768      # Optional: only used if projecting embeddings after concat
  output_dim: 768

decoder_cfg:
  decoder: facebook/bart-base
  lora: true
  input_dim: 1536      # Match fusion output_dim
  hidden_dim: 768
  output_dim: 768
  freeze: false
trainer:
  precision: 32
  accelerator: cuda
  devices: 1
  batch_size: 32
  lr: 1e-4
  device: cuda
  epochs: 50
  output_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/checkpoints
  max_seq_length: 128
  mlm_probability: 0.15
  save_steps: 500
  logging_steps: 100
  log_every_n_steps: 4
  exp_name: SwinBartAudio

data:
  captions_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/captions_csv
  frames_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/frames
  audio_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/mfccs
  batch_size: 32
  num_workers: 0
  pin_memory: false
  use_csv: True

inference:
  batch_size: 1
  num_workers: 0
  pin_memory: false
  max_length: 128
  top_k: 10
  top_p: 0.95
  temperature: 1.0
  image_size: 224
  num_beams: 2
  image_path: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/frames/How To Insert A Nasogastric Tube » NG Tube » Nursing Skills_clip_40.0s_to_183.0s/frame_0001.jpg
  model_path: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/checkpoints/best_model.pth
  video_image_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/frames/How To Insert A Nasogastric Tube » NG Tube » Nursing Skills_clip_40.0s_to_183.0s
  inf_save_dir: /home/hov1syv/Desktop/Personal/research/video-commentary-ai/video_inference_transformer_cls/How To Insert A Nasogastric Tube » NG Tube » Nursing Skills_clip_40.0s_to_183.0s
  
